export interface PhxUser {
    PHX_USER_OID: number,
    USER_ID: string,
    EMPL_NBR: number,
    COMPANY_NAME_CODE: number,
    LAST_UPD_USER: string,
    LAST_UPD_DT_TM: string,
    EMAIL_ID: string | null,
    SMTP_HOST: string | null,
    GUI_USER_PREFERENCES?: string | null,
    USER_ROUTE_TYPE_CD: string,
    CARRIER_GRP_CD: string,
    PHX_ACCESS: string,
    OCA: number,
    CC_RESTRICTED_LEAD_DAYS: number,
    ALLOWABLE_URSA_NETWORK_CDS?: null,
    FDX_COMPANY_GRP: number,
    LAST_LOGIN_DT_TM: string,
    ACTIVE_FLG: string,
    METRIC: string,
    FIRST_NAME: string,
    LAST_NAME: string,
    ALT_EFF_DAYS_VIEW: string,
    DEFAULT_LEG_TYPE_CD?: string | null,
    ORG_CODE: string | null,
    INACTIVE_USER_STATUS?: string;
}